[package]
name = "surgemachinevst"
version = "0.1.0"
authors = ["Frizi <frizi09@gmail.com>"]

[lib]
name = "pendulum"
crate-type = ["cdylib"]

[dependencies]
vst2 = { git = "https://github.com/overdrivenpotato/rust-vst2" }
surgemachine = { path = "../surgemachine" }
